language: rust
rust:
  - stable
  - beta
os:
  - linux
  - windows
  - osx
matrix:
  allow_failures:
    - nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo check
  - cargo fmt --verbose --all -- --check
  - cargo clippy
  - cargo test --verbose $FEATURES -- --nocapture
  - cargo run --example generate_integers
addons:
  apt:
    packages:
      - libssl-dev
notifications:
  email: false
